[package]
name = "sisop1-trab2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap = { version = "3.1.9", features = ["derive"] }
csv = "1.1.6"
serde = { version = "1.0.136", features = ["derive"] }
